"""adding cascade delete in users table relationship with accounts

Revision ID: fdc38f3ad40e
Revises: 213f5d36594f
Create Date: 2025-07-29 14:27:54.332813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc38f3ad40e'
down_revision: Union[str, Sequence[str], None] = '213f5d36594f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
