on: [push, pull_request]

name: Test

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PYTHON_COLORS: 0

    steps:
      - name: Copy files from repo
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
      
      - name: Install dependencies
        run: poetry install
      
      - name: Run Ruff
        run: poetry run ruff check .; poetry run ruff check . --diff
      
      - name: Run Tests
        run: poetry run pytest -s -x --cov=dotum -vv; poetry run coverage html

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
